name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & push
        run: |
          git config user.name "Archit Lal"
          git config user.email "architdraftid@gmail.com"
          git add -A profile-3d-contrib
          git diff --staged --quiet || git commit -m "chore: update 3D contribution graph"
          git push
